name: Fake Self Runner
on:
    push:
        branches:
            - main
   
jobs:
    teste:
        runs-on: [self-hosted]
        steps: 
            - name: Fake Task
              run: echo "Teste self runner"
            - uses: actions/checkout@v4
            - name: Build and push Docker images
              uses: docker/build-push-action@v6.3.0
              with:
                context: ./src
                file: ./src/Dockerfile                
                push: false
                tags: | 
                  cesarags/self-runner:latest